#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "c_dftreal16_common.c"

extern const int   NITER;
extern const int   N;
extern const int   epsilon;
extern const float x_rand16real[];
extern const float X_rand16real[][2];

void dftreal16flat ( const float * arr, /*output:*/ float ** X );

int main()
{
  int i;

  float ** X = malloc( N * sizeof( float* ));

  for (i = 0; i < N; i++)
    {
      X[ i ] = malloc( sizeof( float* ));
    }
  

  /* --- Sanity check --- */

  dftreal16flat( x_rand16real, X );
  
  int ok_all = 1;
  for (i = 0; i < N; i++)
    {
      float*       result_i   = X[ i ];
      const float* expected_i = X_rand16real[ i ];
      float  delta_0 = fabs( result_i[ 0 ] - expected_i[ 0 ] );
      float  delta_1 = fabs( result_i[ 1 ] - expected_i[ 1 ] );
      int ok = EPSILON > delta_0  &&  EPSILON > delta_1;
      /*printf( "%d: %g %g, %g %g, %g %g -> ok: %d\n", i, result_i[ 0 ], result_i[ 1 ], expected_i[ 0 ], expected_i[ 1 ], delta_0, delta_1, ok );*/
      ok_all &= ok;
    }
  /* printf("ok_all: %d\n", ok_all); */
  if (!ok_all)
    {
      fprintf( stderr, "\nERROR: buggy implementation!\n");
      return -1;
    }
  
  /* --- Performance test --- */
  for (i = NITER ; i-- ; )
    dftreal16flat( x_rand16real, X );
  

  /* --- Cleanup --- */
  for (i = N; i--;)
    {
      free( X[ i ] );
    }
  
  free( X );

  /* printf("\nDone.\n"); */
  return 0;
}


void dftreal16flat ( const float * arr, /*output:*/ float ** X )
/* code generated by flatorize_c.js */
{
  /* intermediary calculations */
  float _0 = arr[0];
  float _1 = arr[8];
  float _2 = 0;
  float _3 = _0 + _1;
  float _4 = _0 - _1;
  float _5 = 0 - _2;
  float _6 = arr[4];
  float _7 = arr[12];
  float _8 = _6 + _7;
  float _9 = _6 - _7;
  float _a = _3 + _8;
  float _b = _2 + _2;
  float _c = _3 - _8;
  float _d = _2 - _2;
  float _e = - _9;
  float _f = _4 + _5;
  float _g = _5 + _e;
  float _h = _4 - _5;
  float _i = _5 - _e;
  float _j = arr[2];
  float _k = arr[10];
  float _l = _j + _k;
  float _m = _j - _k;
  float _n = arr[6];
  float _o = arr[14];
  float _p = _n + _o;
  float _q = _n - _o;
  float _r = _l + _p;
  float _s = _l - _p;
  float _t = - _q;
  float _u = _m + _5;
  float _v = _5 + _t;
  float _w = _m - _5;
  float _x = _5 - _t;
  float _y = _a + _r;
  float _z = _b + _b;
  float _10 = _a - _r;
  float _11 = _b - _b;
  float _12 = 0.7071067811865476 * _u + 0.7071067811865475 * _v;
  float _13 = 0.7071067811865476 * _v + -0.7071067811865475 * _u;
  float _14 = _f + _12;
  float _15 = _g + _13;
  float _16 = _f - _12;
  float _17 = _g - _13;
  float _18 = - _s;
  float _19 = _c + _d;
  float _1a = _d + _18;
  float _1b = _c - _d;
  float _1c = _d - _18;
  float _1d = -0.7071067811865475 * _w + 0.7071067811865476 * _x;
  float _1e = -0.7071067811865475 * _x + -0.7071067811865476 * _w;
  float _1f = _h + _1d;
  float _1g = _i + _1e;
  float _1h = _h - _1d;
  float _1i = _i - _1e;
  float _1j = arr[1];
  float _1k = arr[9];
  float _1l = _1j + _1k;
  float _1m = _1j - _1k;
  float _1n = arr[5];
  float _1o = arr[13];
  float _1p = _1n + _1o;
  float _1q = _1n - _1o;
  float _1r = _1l + _1p;
  float _1s = _1l - _1p;
  float _1t = - _1q;
  float _1u = _1m + _5;
  float _1v = _5 + _1t;
  float _1w = _1m - _5;
  float _1x = _5 - _1t;
  float _1y = arr[3];
  float _1z = arr[11];
  float _20 = _1y + _1z;
  float _21 = _1y - _1z;
  float _22 = arr[7];
  float _23 = arr[15];
  float _24 = _22 + _23;
  float _25 = _22 - _23;
  float _26 = _20 + _24;
  float _27 = _20 - _24;
  float _28 = - _25;
  float _29 = _21 + _5;
  float _2a = _5 + _28;
  float _2b = _21 - _5;
  float _2c = _5 - _28;
  float _2d = _1r + _26;
  float _2e = _1r - _26;
  float _2f = 0.7071067811865476 * _29 + 0.7071067811865475 * _2a;
  float _2g = 0.7071067811865476 * _2a + -0.7071067811865475 * _29;
  float _2h = _1u + _2f;
  float _2i = _1v + _2g;
  float _2j = _1u - _2f;
  float _2k = _1v - _2g;
  float _2l = - _27;
  float _2m = _1s + _d;
  float _2n = _d + _2l;
  float _2o = _1s - _d;
  float _2p = _d - _2l;
  float _2q = -0.7071067811865475 * _2b + 0.7071067811865476 * _2c;
  float _2r = -0.7071067811865475 * _2c + -0.7071067811865476 * _2b;
  float _2s = _1w + _2q;
  float _2t = _1x + _2r;
  float _2u = _1w - _2q;
  float _2v = _1x - _2r;
  float _2w = 0.9238795325112867 * _2h + 0.3826834323650898 * _2i;
  float _2x = 0.9238795325112867 * _2i + -0.3826834323650898 * _2h;
  float _2y = 0.7071067811865476 * _2m + 0.7071067811865475 * _2n;
  float _2z = 0.7071067811865476 * _2n + -0.7071067811865475 * _2m;
  float _30 = 0.38268343236508984 * _2s + 0.9238795325112867 * _2t;
  float _31 = 0.38268343236508984 * _2t + -0.9238795325112867 * _2s;
  float _32 = - _2e;
  float _33 = -0.3826834323650897 * _2j + 0.9238795325112867 * _2k;
  float _34 = -0.3826834323650897 * _2k + -0.9238795325112867 * _2j;
  float _35 = -0.7071067811865475 * _2o + 0.7071067811865476 * _2p;
  float _36 = -0.7071067811865475 * _2p + -0.7071067811865476 * _2o;
  float _37 = -0.9238795325112867 * _2u + 0.3826834323650899 * _2v;
  float _38 = -0.9238795325112867 * _2v + -0.3826834323650899 * _2u;
  
  /* output */
  X[0][0] = _y + _2d;
  X[0][1] = _z + _z;
  X[1][0] = _14 + _2w;
  X[1][1] = _15 + _2x;
  X[2][0] = _19 + _2y;
  X[2][1] = _1a + _2z;
  X[3][0] = _1f + _30;
  X[3][1] = _1g + _31;
  X[4][0] = _10 + _11;
  X[4][1] = _11 + _32;
  X[5][0] = _16 + _33;
  X[5][1] = _17 + _34;
  X[6][0] = _1b + _35;
  X[6][1] = _1c + _36;
  X[7][0] = _1h + _37;
  X[7][1] = _1i + _38;
  X[8][0] = _y - _2d;
  X[8][1] = _z - _z;
  X[9][0] = _14 - _2w;
  X[9][1] = _15 - _2x;
  X[10][0] = _19 - _2y;
  X[10][1] = _1a - _2z;
  X[11][0] = _1f - _30;
  X[11][1] = _1g - _31;
  X[12][0] = _10 - _11;
  X[12][1] = _11 - _32;
  X[13][0] = _16 - _33;
  X[13][1] = _17 - _34;
  X[14][0] = _1b - _35;
  X[14][1] = _1c - _36;
  X[15][0] = _1h - _37;
  X[15][1] = _1i - _38;
}

