#include <math.h>
#include <time.h>
#include "cO3_dftreal16_common.h"

double getPI() { return 2.0 * (double)(acos( 1.0 )); }  /* M_PI widely used... but not standard (yet?) */



// dftreal16flat_hh_c_code
void dftreal16flat_hh ( const double * arr, /*output:*/ double ** X )
/* code generated by flatorize_c.js */
{
  /* intermediary calculations */
  double _0 = arr[0];
  double _1 = arr[8];
  double _2 = _0 + _1;
  double _3 = _0 - _1;
  double _4 = arr[4];
  double _5 = arr[12];
  double _6 = _4 + _5;
  double _7 = _4 - _5;
  double _8 = _2 + _6;
  double _9 = _2 - _6;
  double _a = arr[2];
  double _b = arr[10];
  double _c = _a + _b;
  double _d = _a - _b;
  double _e = arr[6];
  double _f = arr[14];
  double _g = _e + _f;
  double _h = _e - _f;
  double _i = _c + _g;
  double _j = _c - _g;
  double _k = _8 + _i;
  double _l = _d - _h;
  double _m = 0.7071067811865475 * _l;
  double _n = _h + _d;
  double _o = -0.7071067811865475 * _n;
  double _p = _3 + _m;
  double _q = - _7 + _o;
  double _r = _3 - _m;
  double _s = _7 + _o;
  double _t = arr[1];
  double _u = arr[9];
  double _v = _t + _u;
  double _w = _t - _u;
  double _x = arr[5];
  double _y = arr[13];
  double _z = _x + _y;
  double _10 = _x - _y;
  double _11 = _v + _z;
  double _12 = _v - _z;
  double _13 = arr[3];
  double _14 = arr[11];
  double _15 = _13 + _14;
  double _16 = _13 - _14;
  double _17 = arr[7];
  double _18 = arr[15];
  double _19 = _17 + _18;
  double _1a = _17 - _18;
  double _1b = _15 + _19;
  double _1c = _15 - _19;
  double _1d = _11 + _1b;
  double _1e = _16 - _1a;
  double _1f = 0.7071067811865475 * _1e;
  double _1g = _1a + _16;
  double _1h = -0.7071067811865475 * _1g;
  double _1i = _w + _1f;
  double _1j = - _10 + _1h;
  double _1k = _w - _1f;
  double _1l = _10 + _1h;
  double _1m = 0.9238795325112867 * _1i + 0.3826834323650898 * _1j;
  double _1n = _12 - _1c;
  double _1o = 0.7071067811865475 * _1n;
  double _1p = _1c + _12;
  double _1q = -0.7071067811865475 * _1p;
  double _1r = 0.38268343236508984 * _1k + 0.9238795325112867 * _1l;
  double _1s = 0.38268343236508984 * _1l - 0.9238795325112867 * _1k;
  
  /* output */
  X[0][0] = _k + _1d;
  X[0][1] = 0;
  X[1][0] = _p + _1m;
  X[1][1] = _q + (0.9238795325112867 * _1j - 0.3826834323650898 * _1i);
  X[2][0] = _9 + _1o;
  X[2][1] = - _j + _1q;
  X[3][0] = _r + _1r;
  X[3][1] = _s + _1s;
  X[4][0] = _8 - _i;
  X[4][1] = - (_11 - _1b);
  X[5][0] = _r - _1r;
  X[5][1] = - (_s - _1s);
  X[6][0] = _9 - _1o;
  X[6][1] = _j + _1q;
  X[7][0] = _p - _1m;
  X[7][1] = - _q + ((- -0.9238795325112867) * _1j - 0.3826834323650899 * _1i);
  X[8][0] = _k - _1d;
  X[8][1] = 0;
}



// dftreal16flat_sr_hh_c_code
void dftreal16flat_sr_hh ( const double * arr, /*output:*/ double ** X )
/* code generated by flatorize_c.js */
{
  /* intermediary calculations */
  double _0 = arr[0];
  double _1 = arr[8];
  double _2 = _0 + _1;
  double _3 = _0 - _1;
  double _4 = arr[4];
  double _5 = arr[12];
  double _6 = _4 + _5;
  double _7 = _4 - _5;
  double _8 = _2 + _6;
  double _9 = _2 - _6;
  double _a = arr[2];
  double _b = arr[10];
  double _c = _a + _b;
  double _d = _a - _b;
  double _e = arr[14];
  double _f = arr[6];
  double _g = _e + _f;
  double _h = _e - _f;
  double _i = _c + _g;
  double _j = _c - _g;
  double _k = _8 + _i;
  double _l = 0.7071067811865476 * _d;
  double _m = 0.7071067811865476 * _h;
  double _n = _l + _m;
  double _o = - _l + _m;
  double _p = _3 + _n;
  double _q = - _7 + _o;
  double _r = _3 - _n;
  double _s = _7 + _o;
  double _t = arr[1];
  double _u = arr[9];
  double _v = _t + _u;
  double _w = _t - _u;
  double _x = arr[5];
  double _y = arr[13];
  double _z = _x + _y;
  double _10 = _x - _y;
  double _11 = _v + _z;
  double _12 = _v - _z;
  double _13 = arr[15];
  double _14 = arr[7];
  double _15 = _13 + _14;
  double _16 = _13 - _14;
  double _17 = arr[3];
  double _18 = arr[11];
  double _19 = _17 + _18;
  double _1a = _17 - _18;
  double _1b = _15 + _19;
  double _1c = _15 - _19;
  double _1d = _11 + _1b;
  double _1e = 0.9238795325112867 * _w - 0.3826834323650898 * _10;
  double _1f = -0.9238795325112867 * _10 - 0.3826834323650898 * _w;
  double _1g = 0.9238795325112867 * _16 + 0.3826834323650898 * _1a;
  double _1h = -0.9238795325112867 * _1a + 0.3826834323650898 * _16;
  double _1i = 0.7071067811865476 * _12;
  double _1j = 0.7071067811865476 * _1c;
  double _1k = _1i + _1j;
  double _1l = - _1i + _1j;
  double _1m = 0.38268343236508984 * _w + 0.9238795325112867 * _10;
  double _1n = 0.38268343236508984 * _10 - 0.9238795325112867 * _w;
  double _1o = 0.38268343236508984 * _16 - 0.9238795325112867 * _1a;
  double _1p = 0.38268343236508984 * _1a + 0.9238795325112867 * _16;
  
  /* output */
  X[0][0] = _k + _1d;
  X[0][1] = 0;
  X[1][0] = _p + (_1e + _1g);
  X[1][1] = _q + (_1f + _1h);
  X[2][0] = _9 + _1k;
  X[2][1] = - _j + _1l;
  X[3][0] = _r + (_1m + _1o);
  X[3][1] = _s + (_1n + _1p);
  X[4][0] = _8 - _i;
  X[4][1] = - (_11 - _1b);
  X[5][0] = _r + (_1f - _1h);
  X[5][1] = - (_s + (_1e - _1g));
  X[6][0] = _9 - _1k;
  X[6][1] = _j + _1l;
  X[7][0] = _p + (_1n - _1p);
  X[7][1] = - (_q + (_1m - _1o));
  X[8][0] = _k - _1d;
  X[8][1] = 0;
}


// dftreal16flat_msr_hh_c_code
void dftreal16flat_msr_hh ( const double * arr, /*output:*/ double ** X )
/* code generated by flatorize_c.js */
{
  /* intermediary calculations */
  double _0 = arr[0];
  double _1 = arr[8];
  double _2 = _0 + _1;
  double _3 = _0 - _1;
  double _4 = arr[4];
  double _5 = arr[12];
  double _6 = _4 + _5;
  double _7 = _4 - _5;
  double _8 = _2 + _6;
  double _9 = _2 - _6;
  double _a = arr[2];
  double _b = arr[10];
  double _c = _a + _b;
  double _d = _a - _b;
  double _e = arr[14];
  double _f = arr[6];
  double _g = _e + _f;
  double _h = _e - _f;
  double _i = _c + _g;
  double _j = _c - _g;
  double _k = _8 + _i;
  double _l = 0.7071067811865476 * _d;
  double _m = 0.7071067811865476 * _h;
  double _n = _l + _m;
  double _o = - _l + _m;
  double _p = _3 + _n;
  double _q = - _7 + _o;
  double _r = _3 - _n;
  double _s = _7 + _o;
  double _t = arr[1];
  double _u = arr[9];
  double _v = _t + _u;
  double _w = _t - _u;
  double _x = arr[5];
  double _y = arr[13];
  double _z = _x + _y;
  double _10 = _x - _y;
  double _11 = _v + _z;
  double _12 = _v - _z;
  double _13 = arr[15];
  double _14 = arr[7];
  double _15 = _13 + _14;
  double _16 = _13 - _14;
  double _17 = arr[3];
  double _18 = arr[11];
  double _19 = _17 + _18;
  double _1a = _17 - _18;
  double _1b = _15 + _19;
  double _1c = _15 - _19;
  double _1d = _11 + _1b;
  double _1e = 0.9238795325112867 * _w - 0.3826834323650898 * _10;
  double _1f = -0.9238795325112867 * _10 - 0.3826834323650898 * _w;
  double _1g = 0.9238795325112867 * _16 + 0.3826834323650898 * _1a;
  double _1h = -0.9238795325112867 * _1a + 0.3826834323650898 * _16;
  double _1i = 0.7071067811865476 * _12;
  double _1j = 0.7071067811865476 * _1c;
  double _1k = _1i + _1j;
  double _1l = - _1i + _1j;
  double _1m = 0.38268343236508984 * _w + 0.9238795325112867 * _10;
  double _1n = 0.38268343236508984 * _10 - 0.9238795325112867 * _w;
  double _1o = 0.38268343236508984 * _16 - 0.9238795325112867 * _1a;
  double _1p = 0.38268343236508984 * _1a + 0.9238795325112867 * _16;
  
  /* output */
  X[0][0] = _k + _1d;
  X[0][1] = 0;
  X[1][0] = _p + (_1e + _1g);
  X[1][1] = _q + (_1f + _1h);
  X[2][0] = _9 + _1k;
  X[2][1] = - _j + _1l;
  X[3][0] = _r + (_1m + _1o);
  X[3][1] = _s + (_1n + _1p);
  X[4][0] = _8 - _i;
  X[4][1] = - (_11 - _1b);
  X[5][0] = _r + (_1f - _1h);
  X[5][1] = - (_s + (_1e - _1g));
  X[6][0] = _9 - _1k;
  X[6][1] = _j + _1l;
  X[7][0] = _p + (_1n - _1p);
  X[7][1] = - (_q + (_1m - _1o));
  X[8][0] = _k - _1d;
  X[8][1] = 0;
}
