// dftreal16flat_sr_hh_c_code
void dftreal16flat_sr_hh ( const double * arr, /*output:*/ double ** X )
/* code generated by flatorize_c.js */
{
  /* intermediary calculations */
  double _0 = arr[0];
  double _1 = arr[8];
  double _2 = _0 + _1;
  double _3 = _0 - _1;
  double _4 = arr[4];
  double _5 = arr[12];
  double _6 = _4 + _5;
  double _7 = _4 - _5;
  double _8 = _2 + _6;
  double _9 = _2 - _6;
  double _a = arr[2];
  double _b = arr[10];
  double _c = _a + _b;
  double _d = arr[14];
  double _e = arr[6];
  double _f = _d + _e;
  double _g = _c + _f;
  double _h = _c - _f;
  double _i = _8 + _g;
  double _j = 0.7071067811865476 * (_a - _b);
  double _k = 0.7071067811865476 * (_d - _e);
  double _l = _j + _k;
  double _m = - _j + _k;
  double _n = _3 + _l;
  double _o = - _7 + _m;
  double _p = _3 - _l;
  double _q = _7 + _m;
  double _r = arr[1];
  double _s = arr[9];
  double _t = _r + _s;
  double _u = _r - _s;
  double _v = arr[5];
  double _w = arr[13];
  double _x = _v + _w;
  double _y = _v - _w;
  double _z = _t + _x;
  double _10 = arr[15];
  double _11 = arr[7];
  double _12 = _10 + _11;
  double _13 = _10 - _11;
  double _14 = arr[3];
  double _15 = arr[11];
  double _16 = _14 + _15;
  double _17 = _14 - _15;
  double _18 = _12 + _16;
  double _19 = _z + _18;
  double _1a = 0.9238795325112867 * _u - 0.3826834323650898 * _y;
  double _1b = -0.9238795325112867 * _y - 0.3826834323650898 * _u;
  double _1c = 0.9238795325112867 * _13 + 0.3826834323650898 * _17;
  double _1d = -0.9238795325112867 * _17 + 0.3826834323650898 * _13;
  double _1e = 0.7071067811865476 * (_t - _x);
  double _1f = 0.7071067811865476 * (_12 - _16);
  double _1g = _1e + _1f;
  double _1h = - _1e + _1f;
  double _1i = 0.38268343236508984 * _u + 0.9238795325112867 * _y;
  double _1j = 0.38268343236508984 * _y - 0.9238795325112867 * _u;
  double _1k = 0.38268343236508984 * _13 - 0.9238795325112867 * _17;
  double _1l = 0.38268343236508984 * _17 + 0.9238795325112867 * _13;
  
  /* output */
  X[0][0] = _i + _19;
  X[0][1] = 0;
  X[1][0] = _n + (_1a + _1c);
  X[1][1] = _o + (_1b + _1d);
  X[2][0] = _9 + _1g;
  X[2][1] = - _h + _1h;
  X[3][0] = _p + (_1i + _1k);
  X[3][1] = _q + (_1j + _1l);
  X[4][0] = _8 - _g;
  X[4][1] = - (_z - _18);
  X[5][0] = _p + (_1b - _1d);
  X[5][1] = - (_q + (_1a - _1c));
  X[6][0] = _9 - _1g;
  X[6][1] = _h + _1h;
  X[7][0] = _n + (_1j - _1l);
  X[7][1] = - (_o + (_1i - _1k));
  X[8][0] = _i - _19;
  X[8][1] = 0;
}
